### ISSUE TITLE
Elevator Generation Bug

### ISSUE THREAD

**Issue by VT-Slacker** [Ellendar/Z2Randomizer#155] opened 2024-01-04 17:02 UTC
Version: 4.3.0 Beta
Flags: RAAN6EAAFAVrWVRKtBcZS+2cLCqBLnjLBJWA
Seed: 38983700
Hash: 5ALRJ6
Issue: P2 second elevator. Bottom floor goes into an invalid room.  Cannot reach palace boss.
![image](https://github.com/Ellendar/Z2Randomizer/assets/155663790/d79aade0-196c-47be-a7b4-19b7316570b8)

**Comment by MiR4i** [comment] 2024-01-04 17:04
Possible duplicate of #137

**Comment by VT-Slacker** [comment] 2024-01-04 17:19
P1 also goes to a black screen in the middle of the palace.  Can't Up+A to get out.

**Comment by Ellendar** [comment] 2024-01-06 16:51
The most likely cause of this is an error in the palace saving memory management, but jrowe completely redid that system, so even if I track a fix down, the problem won't exist anymore. (Likely replaced by new problems). Closing this and we can add new tickets as needed on the new release.

**Closed by Ellendar** 2024-01-06 16:51 UTC
