### ISSUE TITLE
Unable To Generate ROM (4.2.1)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#82] opened 2023-07-15 06:59 UTC
The following flagset and seed cause an exception in the application when attempting to generate a ROM.

Version: `4.2.1 3f3c979`
Flagset: `RAAN6AAFesXtN1Tdt0g$8v4cYf4XT7AAWA`
Seed: `4869559`
Error:
![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/f80ba03c-c7eb-4d2f-89fe-b3de47381b93)

Furthermore, if you select a specific biome for the West (e.g. Vanilla-Like / Islands / Canyon / Caldera / Mountainous), the seed will generate just fine, but switching back to "Random (No Vanilla)" throws an error.

**Comment by MiR4i** [comment] 2023-07-16 06:13
In the event it helps narrow down an issue, here is another seed I stumbled upon with the same issue:

Flagset: `AAAN6AAFesXtN1TeM0g$8v4cX#4XR7AAWA`
Seed: `249867437`

**Comment by Ellendar** [comment] 2023-07-16 22:01
This issue was caused by the same bug as the duplicate boots seed and was fixed by that fix. Also I was unable to reproduce any error switching bomes. If there is still an issue on the new version let me know.

**Closed by Ellendar** 2023-07-16 22:01 UTC
