### ISSUE TITLE
Multiples Candles in Item Pool (853305789) (4.3.0 7a7e62d)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#134] opened 2023-12-22 09:37 UTC
Started this seed with the Candle (random item shuffle), but two additional Candles were available in the seed (P3 & P6), both of which contained multiple item rooms (also documented in #133).

Flagset: `hEAEiqAFerX2WTVKtVeRf+2csmv@smiyAAWA`
Seed: `853305789`

**Comment by Ellendar** [comment] 2023-12-27 00:36
This was caused by the anti-cheese boss item room that has a upward staircase and doesn't require a key being marked as isBossRoom:true, so that room was actually the boss room. Because it wasn't the item room, the item was never set to be the item it should be, so it stayed as the default, which for that room is candle.

Fixed that room (and several others) to have correct isBossRoom and hasBoss values.

**Closed by Ellendar** 2023-12-27 00:36 UTC
